---
title: "Corr"
author: "Patience Bosompemaa"
date: "2024-10-28"
output: html_document
---

```{r}
library(sf)
library(ggplot2)
library(zoo)
library(dplyr)
library(magrittr)
library(tidyverse)
library(lubridate)
library(patchwork)
library(ggpubr)
library(metan)
library(FactoMineR)
library(factoextra)
```

```{r}
pc <- read_csv("C:/Users/p739b253/OneDrive - University of Kansas/FEWtures/Manuscript2/Corr_data1new.csv")
names(pc)
```

```{r}
dim(PCA) # to see the dimension of the data ie. the number of rows and columns in the dataset
corr_coef(pc[1:21]) #to make a matrix of correlation between the variables which are continuous in nature
```
```{r}
library(corrplot)
D<- pc[1:21]
```

```{r}M = cor(D)
corrplot(M, method ='number', order= 'alphabet', type='lower')
```


```{r}
b<- plot(corr_coef(pc[1:21]))
b
```

```{r}
# Save the plot
ggsave(filename = "Corr2_withoutParameters.png", plot = b, path = "C:\\Users\\p739b253\\OneDrive - University of Kansas\\FEWtures\\Manuscript2\\IMAGES\\LR_KS")
```















